// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZdPerkYdX6I-SG05UEQqrSP1aW3jv44c',
    appId: '1:786686473870:web:babcdc51f733892909fbdf',
    messagingSenderId: '786686473870',
    projectId: 'wisdomwing-7734c',
    authDomain: 'wisdomwing-7734c.firebaseapp.com',
    storageBucket: 'wisdomwing-7734c.appspot.com',
    measurementId: 'G-3MNVYNDMC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbLwXuwKF-hLwrkyh94Y7yO8S2haOZBbI',
    appId: '1:786686473870:android:f47893e540eac86b09fbdf',
    messagingSenderId: '786686473870',
    projectId: 'wisdomwing-7734c',
    storageBucket: 'wisdomwing-7734c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7EHey3k-nkagWWB0KpW2059qnfkYbx78',
    appId: '1:786686473870:ios:7f3384219a8406a309fbdf',
    messagingSenderId: '786686473870',
    projectId: 'wisdomwing-7734c',
    storageBucket: 'wisdomwing-7734c.appspot.com',
    iosBundleId: 'com.example.wisdomWings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7EHey3k-nkagWWB0KpW2059qnfkYbx78',
    appId: '1:786686473870:ios:7f3384219a8406a309fbdf',
    messagingSenderId: '786686473870',
    projectId: 'wisdomwing-7734c',
    storageBucket: 'wisdomwing-7734c.appspot.com',
    iosBundleId: 'com.example.wisdomWings',
  );
}
